# Generated by Django 6.0.5 on 2026-05-24 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0002_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='nama',
            new_name='name',
        ),
    ]
